/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.0/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    implementation("com.diffplug.durian:durian:2.0") // one-line lambda exception handling
    implementation("com.google.apis:google-api-services-books:v1-rev20201021-1.30.10")
    implementation("com.omertron:API-OMDB:1.5")
    
    runtimeOnly("org.slf4j:slf4j-log4j12:1.7.30")
    
    testImplementation("junit:junit:4.12")
}

application {
    // Define the main class for the application.
    mainClassName = "it.unibo.sampleapp.App"
}
